export interface WordleWord {
    word: string; // exactly 5 letters, uppercase
    hint: string;
}

export const WORDLE_WORDS: WordleWord[] = [
    { word: 'VIRAT', hint: 'A legendary Indian modern-day batsman ' },
    { word: 'KOHLI', hint: 'A legendary Indian modern-day batsman ' },
    { word: 'SMITH', hint: 'Australian batting great known for his unique technique' },
    { word: 'STUMP', hint: 'One of three wooden posts' },
    { word: 'WIDES', hint: 'Extra runs' },
    { word: 'CATCH', hint: 'Dismissal method' },
    { word: 'SLOGS', hint: 'Aggressive, unrefined shots' },
    { word: 'OVALS', hint: 'Famous London cricket ground, plural form' },
    { word: 'TESTS', hint: 'The longest format of the game, played over 5 days' },
    { word: 'CRASH', hint: 'What a batting collapse might be called' },
    { word: 'PITCH', hint: 'The strip where the action happens' },
    { word: 'SPINS', hint: 'What a leg-break or off-break bowler makes the ball do' },
    { word: 'DUCKS', hint: 'Getting out, plural' },
    { word: 'DRIVE', hint: 'played along the ground' },
    { word: 'GULLY', hint: 'A fielding position' },
    { word: 'BAILS', hint: 'Gilly ukhad di' },
    { word: 'SIXES', hint: 'Shots that has all eyes on' },
    { word: 'SWING', hint: 'Lateral movement of the ball through the air' },
    { word: 'STOKE', hint: 'Sounds like the surname of England' },
    { word: 'GAYLE', hint: 'Explosive West Indian' },
    { word: 'DHONI', hint: 'Legendary Indian captain' },
    { word: 'WARNE', hint: 'Australian legend' },
    { word: 'RAINA', hint: 'Indian middle-order batsman, strong player of spin' },
    { word: 'DEVON', hint: 'English county, or a common first name' },
    { word: 'BOULT', hint: 'New Zealand fast bowler' },
    { word: 'STARC', hint: 'Australian pace spearhead' },
    { word: 'AARON', hint: 'Indian fast bowler first name, or biblical name' },
    { word: 'ASHES', hint: 'Historic Test series' },
    { word: 'BOWLS', hint: 'What a bowler does with the ball' },
    { word: 'RAHUL', hint: 'I can do everything you ask' },
    { word: 'SIRAJ', hint: 'Official ID' },

    { word: 'CHASE', hint: 'Batting with score pressure' },
    { word: 'CHUCK', hint: 'Illegal' },
    { word: 'CLEAN', hint: 'Describes a well-executed shot or dismissal' },
    { word: 'COVER', hint: 'A fielding position on the off side' },
    { word: 'DELAY', hint: 'What rain does' },
    { word: 'DODGE', hint: 'What a batsman does to avoid a bouncer' },
    { word: 'DROPS', hint: 'What fielders do when they miss a catch' },
    { word: 'EDGES', hint: 'Faint contact to the keeper' },
    { word: 'FIELD', hint: 'The area where fielders are positioned' },
    { word: 'FLICK', hint: 'A wristy shot played off the pads' },
    { word: 'GLOVE', hint: 'What a wicketkeeper wears' },
    { word: 'GRASS', hint: 'What covers the outfield of a cricket ground' },
    { word: 'GREEN', hint: 'Describes a pitch with more grass, favouring bowlers' },
    { word: 'GRIPS', hint: 'How a bowler holds the ball, plural' },
    { word: 'HITER', hint: 'what do we call a slogger' },
    { word: 'HOOKS', hint: 'Shots played against a short-pitched delivery, plural' },
    { word: 'KNOCK', hint: 'Informal term for a batting innings' },
    { word: 'LEADS', hint: 'What a team does when ahead on runs' },
    { word: 'LEAPS', hint: 'What a fielder does to take a spectacular catch' },
    { word: 'LEVEL', hint: 'When scores are tied' },
    { word: 'LOFTS', hint: 'Shots hit in the air' },
    { word: 'LOOPY', hint: 'Describes a slow, high-arcing delivery' },
    { word: 'LOWER', hint: 'Describes the tail-end of a batting order' },
    { word: 'LUNCH', hint: 'The mid-day break during a Test match' },
    { word: 'MATCH', hint: 'A single game of cricket' },
    { word: 'MOVES', hint: 'What the ball does in the air' },
    { word: 'NASTY', hint: 'Describes a particularly sharp bouncer or spell' },
    { word: 'NICKS', hint: 'Slang for thin edges' },
    { word: 'NOISE', hint: 'What the crowd makes' },
    { word: 'ORDER', hint: 'The sequence in which batsmen come in to bat' },
    { word: 'OVERS', hint: 'Sets of six legal deliveries, plural' },
    { word: 'PACER', hint: 'A bowler' },
    { word: 'PADUP', hint: 'you are next to bat' },
    { word: 'PANIC', hint: 'What a batting side might feel during a collapse' },
    { word: 'PLAYS', hint: 'What a batsman does to a delivery, present tense' },
    { word: 'POINT', hint: 'A fielding position square of the wicket on the off side' },
    { word: 'POWER', hint: 'What "___play" refers to in limited-overs cricket' },
    { word: 'PULLS', hint: 'Shots played best by all the R"s' },
    { word: 'QUICK', hint: 'Another word for a fast bowler' },
    { word: 'ROUND', hint: 'Describes a bowler\'s "___ the wicket" approach' },
    { word: 'SCOOP', hint: 'A modern, unorthodox shot played over the keeper' },
    { word: 'SCORE', hint: 'The total runs made by a team or player' },
    { word: 'SEAMS', hint: 'The raised stitching on a cricket ball' },
    { word: 'SHOTS', hint: 'What batsmen play' },
    { word: 'SIDES', hint: 'Another word for teams' },
    { word: 'SIXER', hint: 'A shot that clears the boundary without bouncing' },
    { word: 'SLIPS', hint: 'Fielding positions behind the batsman' },
    { word: 'SLOGS', hint: 'Aggressive, unrefined hitting shots' },

    { word: 'SPEED', hint: 'What a fast bowler generates with the ball' },
    { word: 'SPELL', hint: 'A continuous stretch of overs' },
    { word: 'SQUAD', hint: 'The full group of players' },
    { word: 'STARS', hint: 'What top-performing players are often called' },
    { word: 'SWEEP', hint: 'A cross-batted shot' },
    { word: 'TAKEN', hint: 'What a catch or wicket has been, past tense' },
    { word: 'THROW', hint: 'What a fielder does to return the ball' },
    { word: 'TIGHT', hint: 'Describes a close, low-scoring finish' },
    { word: 'TIMED', hint: 'Describes a perfectly executed shot' },
    { word: 'UPPER', hint: 'Describes the top order of a batting lineup' },
    { word: 'VENUE', hint: 'The location where a match is played' },
    { word: 'WATCH', hint: 'What commentators tell viewers to do closely' },
    { word: 'WIDES', hint: 'Deliveries bowled out of the batsman\'s reach' },
    { word: 'SHAMI', hint: 'Sexiest seam position' },
    { word: 'BABAR', hint: 'Some people loves his cover drive(sarcasm)' }

];