export interface WordleWord {
    word: string; // exactly 5 letters, uppercase
    hint: string;
}

export const WORDLE_WORDS: WordleWord[] = [
    { word: 'VIRAT', hint: 'A legendary Indian modern-day batsman ' },
    { word: 'KOHLI', hint: 'A legendary Indian modern-day batsman ' },
    { word: 'SMITH', hint: 'Australian batting great known for his unique technique' },
    { word: 'STUMP', hint: 'One of three wooden posts that hold the bails' },
    { word: 'WIDES', hint: 'Extra runs given when the ball is out of reach of the batsman' },
    { word: 'CATCH', hint: 'Dismissal method when the ball is caught before touching ground' },
    { word: 'SLOGS', hint: 'Aggressive, unrefined shots aimed at big hitting' },
    { word: 'OVALS', hint: 'Famous London cricket ground, plural form' },
    { word: 'TESTS', hint: 'The longest format of the game, played over 5 days' },
    { word: 'CRASH', hint: 'What a batting collapse might be called' },
    { word: 'PITCH', hint: 'The 22-yard strip where the action happens' },
    { word: 'SPINS', hint: 'What a leg-break or off-break bowler makes the ball do' },
    { word: 'DUCKS', hint: 'Getting out without scoring, plural' },
    { word: 'DRIVE', hint: 'A classic batting shot played along the ground' },
    { word: 'GULLY', hint: 'A fielding position between slip and point' },
    { word: 'BAILS', hint: 'The two small pieces of wood sitting atop the stumps' },
    { word: 'SIXES', hint: 'Shots that clear the boundary without bouncing, plural' },
    { word: 'SWING', hint: 'Lateral movement of the ball through the air' },
    { word: 'STOKE', hint: 'Sounds like the surname of England\'s 2019 World Cup hero' },
    { word: 'GAYLE', hint: 'Explosive West Indian opener known as the "Universe Boss"' },
    { word: 'DHONI', hint: 'Legendary Indian wicketkeeper-captain, "Captain Cool"' },
    { word: 'WARNE', hint: 'Australian leg-spin legend' },
    { word: 'RAINA', hint: 'Indian middle-order batsman, strong player of spin' },
    { word: 'DEVON', hint: 'English county, or a common first name' },
    { word: 'BOULT', hint: 'New Zealand left-arm fast bowler' },
    { word: 'STARC', hint: 'Australian left-arm pace spearhead' },
    { word: 'AARON', hint: 'Indian fast bowler first name, or biblical name' },
    { word: 'ASHES', hint: 'Historic Test series between England and Australia' },
    { word: 'BOWLS', hint: 'What a bowler does with the ball, present tense' },
    { word: 'RAHUL', hint: 'I can do everything you ask' },
    { word: 'SIRAJ', hint: 'Official ID' },

    { word: 'CHASE', hint: 'Batting second and pursuing a target score' },
    { word: 'CHUCK', hint: 'Illegal bowling action term' },
    { word: 'CLEAN', hint: 'Describes a well-executed shot or dismissal, "___ bowled"' },
    { word: 'COVER', hint: 'A fielding position on the off side' },
    { word: 'CRUSE', hint: '' },
    { word: 'DEUCE', hint: '' },
    { word: 'DELAY', hint: 'What rain often causes to a match' },
    { word: 'DODGE', hint: 'What a batsman does to avoid a bouncer' },
    { word: 'DROPS', hint: 'What fielders do when they miss a catch' },
    { word: 'EDGES', hint: 'Faint contact with the bat before going to the keeper' },
    { word: 'FIELD', hint: 'The area where fielders are positioned' },
    { word: 'FLICK', hint: 'A wristy shot played off the pads' },
    { word: 'FLOOR', hint: '' },
    { word: 'GLOVE', hint: 'What a wicketkeeper wears' },
    { word: 'GRASS', hint: 'What covers the outfield of a cricket ground' },
    { word: 'GREEN', hint: 'Describes a pitch with more grass, favouring bowlers' },
    { word: 'GRIPS', hint: 'How a bowler holds the ball, plural' },
    { word: 'HITER', hint: '' },
    { word: 'HOOKS', hint: 'Shots played against a short-pitched delivery, plural' },
    { word: 'KNOCK', hint: 'Informal term for a batting innings' },
    { word: 'LEADS', hint: 'What a team does when ahead on runs, present tense' },
    { word: 'LEAPS', hint: 'What a fielder does to take a spectacular catch' },
    { word: 'LEVEL', hint: 'When scores are tied' },
    { word: 'LOFTS', hint: 'Shots hit in the air, plural' },
    { word: 'LOOPY', hint: 'Describes a slow, high-arcing delivery' },
    { word: 'LOWER', hint: 'Describes the tail-end of a batting order' },
    { word: 'LUNCH', hint: 'The mid-day break during a Test match' },
    { word: 'MATCH', hint: 'A single game of cricket' },
    { word: 'MOVES', hint: 'What the ball does in the air when it swings' },
    { word: 'NASTY', hint: 'Describes a particularly sharp bouncer or spell' },
    { word: 'NEEDS', hint: 'What a chasing team "___ runs" to win' },
    { word: 'NICKS', hint: 'Slang for thin edges, plural' },
    { word: 'NOISE', hint: 'What the crowd makes after a big six' },
    { word: 'ORDER', hint: 'The sequence in which batsmen come in to bat' },
    { word: 'OVERS', hint: 'Sets of six legal deliveries, plural' },
    { word: 'PACER', hint: 'A fast bowler' },
    { word: 'PADUP', hint: '' },
    { word: 'PANIC', hint: 'What a batting side might feel during a collapse' },
    { word: 'PLAYS', hint: 'What a batsman does to a delivery, present tense' },
    { word: 'POINT', hint: 'A fielding position square of the wicket on the off side' },
    { word: 'POWER', hint: 'What "___play" refers to in limited-overs cricket' },
    { word: 'PULLS', hint: 'Shots played against a short ball, plural' },
    { word: 'QUICK', hint: 'Another word for a fast bowler' },
    { word: 'ROUND', hint: 'Describes a bowler\'s "___ the wicket" approach' },
    { word: 'SCOOP', hint: 'A modern, unorthodox shot played over the keeper' },
    { word: 'SCORE', hint: 'The total runs made by a team or player' },
    { word: 'SEAMS', hint: 'The raised stitching on a cricket ball, plural' },
    { word: 'SHOTS', hint: 'What batsmen play, plural' },
    { word: 'SIDES', hint: 'Another word for teams, plural' },
    { word: 'SIXER', hint: 'A shot that clears the boundary without bouncing' },
    { word: 'SLIPS', hint: 'Fielding positions behind the batsman, plural' },
    { word: 'SLOGS', hint: 'Aggressive, unrefined hitting shots' },

    { word: 'SPEED', hint: 'What a fast bowler generates with the ball' },
    { word: 'SPELL', hint: 'A continuous stretch of overs bowled by one bowler' },
    { word: 'SQUAD', hint: 'The full group of selected players for a series' },
    { word: 'STARS', hint: 'What top-performing players are often called' },
    { word: 'SWEEP', hint: 'A cross-batted shot played against a spinner' },
    { word: 'TAKEN', hint: 'What a catch or wicket has been, past tense' },
    { word: 'THROW', hint: 'What a fielder does to return the ball' },
    { word: 'TIGHT', hint: 'Describes a close, low-scoring finish' },
    { word: 'TIMED', hint: 'Describes a perfectly executed shot' },
    { word: 'UPPER', hint: 'Describes the top order of a batting lineup' },
    { word: 'VENUE', hint: 'The location where a match is played' },
    { word: 'WATCH', hint: 'What commentators tell viewers to do closely' },
    { word: 'WIDES', hint: 'Deliveries bowled out of the batsman\'s reach' },
];